app/questions/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField
from wtforms.validators import DataRequired


class CreateListForm(FlaskForm):
    title = TextAreaField('Title', validators=[DataRequired()])
    submit = SubmitField('Submit')


class CreateQuestionForm(FlaskForm):
    question = TextAreaField('Question', validators=[DataRequired()])
    answer = TextAreaField('Answer', validators=[DataRequired()])
    submit = SubmitField('Submit')


class CreateFlavourTextForm(FlaskForm):
    text = TextAreaField('Flavour Text', validators=[DataRequired()])
    category = StringField('Category', validators=[DataRequired()])
    submit = SubmitField('Submit')

app/questions/__init__.py
from . import routes

from .routes import *

app/questions/routes.py
from flask import Blueprint, render_template, jsonify, redirect, url_for, request
from app.db import db, QuestionList, Question, FlavourText
from .forms import CreateListForm, CreateQuestionForm, CreateFlavourTextForm


bp = Blueprint('questions', __name__)


@bp.route('/test')
def dummy_route():
    return jsonify([{'question': 'Why did the chicken cross the road?', 'answer': 'boffa'}])


@bp.route('/')
def view_lists():
    lists = QuestionList.query.all()
    return render_template('questions/index.html', lists=lists)

@bp.route('/list/<list_id>')
def view_list(list_id):
    qlist = QuestionList.query.filter_by(id=list_id).first()
    return render_template('questions/list.html', list=qlist)


@bp.route('/create', methods=['GET', 'POST'])
def create_list():
    form = CreateListForm()
    if form.validate_on_submit():
        qlist = QuestionList()
        qlist.title = form.title.data
        db.session.add(qlist)
        db.session.commit()
        return redirect(url_for('questions.view_lists'))
    return render_template('questions/create_list.html', form=form)


@bp.route('/delete/<list_id>')
def delete_list(list_id):
    qlist = QuestionList.query.filter_by(id=list_id)
    if qlist is not None:
        qlist.delete()
        db.session.commit()
    return redirect(url_for('questions.view_lists'))


@bp.route('/list/<list_id>/create_question', methods=['GET', 'POST'])
def create_question(list_id):
    qlist = QuestionList.query.filter_by(id=list_id).first()
    form = CreateQuestionForm(request.form)
    if form.validate_on_submit():
        question = Question()
        question.question = form.question.data
        question.answer = form.answer.data
        question.list = qlist
        db.session.add(question)
        db.session.commit()
        return redirect(url_for('questions.view_list', list_id=list_id))
    return render_template('questions/create_question.html', form=form, list=qlist)


@bp.route('/list/<list_id>/edit_question/<question_id>', methods=['GET', 'POST'])
def edit_question(list_id, question_id):
    qlist = QuestionList.query.filter_by(id=list_id).first()
    question = Question.query.filter_by(id=question_id).first()
    form = CreateQuestionForm(obj=question)
    if form.validate_on_submit():
        question.question = form.question.data
        question.answer = form.answer.data
        question.list = QuestionList.query.filter_by(id=list_id).first()
        db.session.add(question)
        db.session.commit()
        return redirect(url_for('questions.view_list', list_id=list_id))
    return render_template('questions/edit_question.html', form=form, list=qlist, question=question)


@bp.route('/list/<list_id>/question/<question_id>')
def view_question(list_id, question_id):
    qlist = QuestionList.query.filter_by(id=list_id).first()
    question = Question.query.filter_by(id=question_id).first()
    return render_template('questions/question.html', list=qlist, question=question)


@bp.route('/list/<list_id>/delete_question/<question_id>')
def delete_question(list_id, question_id):
    question = Question.query.filter_by(id=question_id)
    if question is not None:
        question.delete()
        db.session.commit()
    return redirect(url_for('questions.view_list', list_id=list_id))


@bp.route('/list/<list_id>/create_flavour_text', methods=['GET', 'POST'])
def create_flavour_text(list_id):
    qlist = QuestionList.query.filter_by(id=list_id).first()
    form = CreateFlavourTextForm(request.form)
    if form.validate_on_submit():
        flavour_text = FlavourText()
        flavour_text.text = form.text.data
        flavour_text.category = form.category.data
        flavour_text.list = qlist
        db.session.add(flavour_text)
        db.session.commit()
        return redirect(url_for('questions.view_list', list_id=list_id))
    return render_template('questions/create_flavour_text.html', form=form, list=qlist)


@bp.route('/list/<list_id>/edit_flavour_text/<flavour_text_id>', methods=['GET', 'POST'])
def edit_flavour_text(list_id, flavour_text_id):
    qlist = QuestionList.query.filter_by(id=list_id).first()
    flavour_text = FlavourText.query.filter_by(id=flavour_text_id).first()
    form = CreateFlavourTextForm(request.form, obj=flavour_text)
    if form.validate_on_submit():
        flavour_text.text = form.text.data
        flavour_text.category = form.category.data
        flavour_text.list = QuestionList.query.filter_by(id=list_id).first()
        db.session.add(flavour_text)
        db.session.commit()
        return redirect(url_for('questions.view_list', list_id=list_id))
    return render_template('questions/edit_flavour_text.html', form=form, list=qlist, flavour_text=flavour_text)


@bp.route('/list/<list_id>/flavour_text/<flavour_text_id>')
def view_flavour_text(list_id, flavour_text_id):
    qlist = QuestionList.query.filter_by(id=list_id).first()
    flavour_text = FlavourText.query.filter_by(id=flavour_text_id).first()
    return render_template('questions/flavour_text.html', list=qlist, flavour_text=flavour_text)


@bp.route('/list/<list_id>/delete_flavour_text/<flavour_text_id>')
def delete_flavour_text(list_id, flavour_text_id):
    flavour_text = FlavourText.query.filter_by(id=flavour_text_id)
    if flavour_text is not None:
        flavour_text.delete()
        db.session.commit()
    return redirect(url_for('questions.view_list', list_id=list_id))

templates/questions/create_flavour_text.html
{% extends 'base.html' %}
{% from '_formhelpers.html' import render_field %}

{% block nav %}
{% with current='questions' %}
{% include 'nav.html' %}
{% endwith %}
{% endblock %}


{% block content %}
<header class="alignment">
  <div>
    <img class='logoImage' alt='logo' src="{{ url_for('static', filename='images/manyHex.png')}}">
  </div>
  <div>
    <h1 class="title">breakingboundr.io</h1>
  </div>
</header>
<main>
  <div class='card gapsBetween lbbg'>
    <form class="formStyle" action="" method="post" novalidate>
        {{ form.hidden_tag() }}
        <dl class="form-group">
            {{ render_field(form.text, class='form-control titlecard', placeholder='Flavour Text') }}
            {{ render_field(form.category, class='form-control titlecard', placeholder='Category') }}
        </dl>
        <dl>
            {{ render_field(form.submit, class='btn btn-lg btn-secondary btn-block') }}
          <div class="text-center">
            <a href="{{ url_for('questions.view_list', list_id=list.id) }}">Cancel</a>
          </div>
        </dl>
    </form>
  </div>
</main>
{% endblock %}

{% block footer %}
{% include 'footer.html' %}
{% endblock %}

templates/questions/create_list.html
{% extends 'base.html' %}
{% from '_formhelpers.html' import render_field %}

{% block nav %}
{% with current='questions' %}
{% include 'nav.html' %}
{% endwith %}
{% endblock %}


{% block content %}
<header class="alignment">
  <div>
    <img class='logoImage' alt='logo' src="{{ url_for('static', filename='images/manyHex.png')}}">
  </div>
  <div>
    <h1 class="title">breakingboundr.io</h1>
  </div>
</header>
<main>
  <div class='card gapsBetween lbbg'>
      <form class="formStyle" action="" method="post" novalidate>
          {{ form.hidden_tag() }}
          <dl class="form-group">
            {{ render_field(form.title, class='form-control titlecard', placeholder='What is your question list about?') }}
          </dl>
          <dl>
            {{ render_field(form.submit, class='btn btn-lg btn-secondary btn-block') }}
            <div class="text-center">
              <a href="{{ url_for('questions.view_lists') }}">Cancel</a>
            </div>
          </dl>
      </form>
    </div>
</main>
{% endblock %}

{% block footer %}
{% include 'footer.html' %}
{% endblock %}

templates/questions/create_question.html
{% extends 'base.html' %}
{% from '_formhelpers.html' import render_field %}

{% block nav %}
{% with current='questions' %}
{% include 'nav.html' %}
{% endwith %}
{% endblock %}


{% block content %}
<header class="alignment">
  <div>
    <img class='logoImage' alt='logo' src="{{ url_for('static', filename='images/manyHex.png')}}">
  </div>
  <div>
    <h1 class="title">breakingboundr.io</h1>
  </div>
</header>
<main>
  <body>
    <div class='card gapsBetween'>
      <h2>Add any questions you want to be included in the game</h2>
      <form class="formStyle" action="" method="post" novalidate>
          {{ form.hidden_tag() }}
        <dl class="form-group" id='fontMain'>
          {{ render_field(form.question, class='form-control titlecard', placeholder='Question') }}
          {{ render_field(form.answer, class='form-control titlecard', placeholder='Answer') }}
        </dl>
        <dl>
          {{ render_field(form.submit, class='btn btn-lg btn-secondary btn-block') }}
          <div class="text-center">
            <a href="{{ url_for('questions.view_list', list_id=list.id) }}">Cancel</a>
          </div>
        </dl>
      </form>
    </div>
  </body>
</main>
{% endblock %}

{% block footer %}
{% include 'footer.html' %}
{% endblock %}

templates/questions/edit_flavour_text.html
{% extends 'base.html' %}
{% from '_formhelpers.html' import render_field %}

{% block nav %}
{% with current='questions' %}
{% include 'nav.html' %}
{% endwith %}
{% endblock %}


{% block content %}
<header class="alignment">
  <div>
    <img class='logoImage' alt='logo' src="{{ url_for('static', filename='images/manyHex.png')}}">
  </div>
  <div>
    <h1 class="title">breakingboundr.io</h1>
  </div>
</header>
<main>
  <div class='card gapsBetween lbbg'>
      <form class="formStyle" action="" method="post" novalidate>
          {{ form.hidden_tag() }}
          <dl class="form-group">
              {{ render_field(form.text, class='form-control titlecard', placeholder='Flavour Text') }}
              {{ render_field(form.category, class='form-control titlecard', placeholder='Category') }}
          </dl>
          <dl>
              {{ render_field(form.submit, class='btn btn-lg btn-secondary btn-block') }}
          </dl>
      </form>
      <p class="text-center"><a href="{{ url_for('questions.delete_flavour_text', list_id=list.id, flavour_text_id=flavour_text.id)}}">Delete flavour text</a></p>
    </div>
</main>
{% endblock %}

{% block footer %}
{% include 'footer.html' %}
{% endblock %}

templates/questions/edit_question.html
{% extends 'base.html' %}
{% from '_formhelpers.html' import render_field %}

{% block nav %}
{% with current='questions' %}
{% include 'nav.html' %}
{% endwith %}
{% endblock %}


{% block content %}
<header class="alignment">
  <div>
    <img class='logoImage' alt='logo' src="{{ url_for('static', filename='images/manyHex.png')}}">
  </div>
  <div>
    <h1 class="title">breakingboundr.io</h1>
  </div>
</header>
<main>
  <div class='card gapsBetween lbbg'>
      <form class="formStyle" action="" method="post" novalidate>
          {{ form.hidden_tag() }}
          <dl class="form-group">
              {{ render_field(form.question, class='form-control titlecard', placeholder='Question') }}
              {{ render_field(form.answer, class='form-control titlecard', placeholder='Answer') }}
          </dl>
          <dl>
              {{ render_field(form.submit, class='btn btn-lg btn-secondary btn-block') }}
          </dl>
      </form>
      <p class="text-center"><a href="{{ url_for('questions.delete_question', list_id=list.id, question_id=question.id)}}">Delete question</a></p>
    </div>
</main>
{% endblock %}

{% block footer %}
{% include 'footer.html' %}
{% endblock %}

templates/questions/index.html
{% extends 'base.html' %}

{% block nav %}
{% with current='questions' %}
{% include 'nav.html' %}
{% endwith %}
{% endblock %}


{% block content %}
<header class="alignment">
  <div>
    <img class='logoImage' alt='logo' src="{{ url_for('static', filename='images/manyHex.png')}}">
  </div>
  <div>
    <h1 class="title">breakingboundr.io</h1>
  </div>
</header>
<main>
  <div class="card text-center lbbg">
    <div class="card-body">
      <h5 class="card-title largeFont">Question Lists</h5>
        <ul class="list-group list-group-flush">
            {% for list in lists %}
            <a class="list-group-item list-group-item-active" href="{{ url_for('questions.view_list', list_id=list.id)}}">{{ list.title }}</a>
            {% endfor %}
            <a class="list-group-item list-group-item-active" href="{{ url_for('questions.create_list')}}">Create new list</a>
        </ul>
    </div>
  </div>
</main>
{% endblock %}

{% block footer %}
{% include 'footer.html' %}
{% endblock %}

templates/questions/list.html
{% extends 'base.html' %}

{% block nav %}
{% with current='questions' %}
{% include 'nav.html' %}
{% endwith %}
{% endblock %}


{% block content %}
<header class="alignment">
  <div>
    <img class='logoImage' alt='logo' src="{{ url_for('static', filename='images/manyHex.png')}}">
  </div>
  <div>
    <h1 class="title">breakingboundr.io</h1>
  </div>
</header>
<main>
  <div class="container-fluid">
    <div class="row">
      <div class="col-5 offset-1 mb-3">
        <div class="card text-center lbbg">
          <div class="card-body">
            <h5 class="card-title largeFont"><a href="{{ url_for('questions.view_lists') }}">View all lists</a></h5>
          </div>
        </div>
      </div>
      <div class="col-5 mb-3">
        <div class="card text-center lbbg">
          <div class="card-body">
            <h5 class="card-title largeFont"><a href="{{ url_for('questions.delete_list', list_id=list.id) }}">Delete this list</a></h5>
          </div>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-5 offset-1">
        <div class="card text-center lbbg">
          <div class="card-body">
            <h5 class="card-title largeFont">{{ list.title }}: Questions</h5>
              <ul class="list-group list-group-flush">
                  {% for question in list.questions %}
                  <li class="list-group-item list-group-item-active"><a href="{{ url_for('questions.edit_question', list_id=list.id, question_id=question.id)}}">{{ question.question }}</a>: {{ question.answer }}</li>
                  {% endfor %}
                  <a class="list-group-item list-group-item-active" href="{{ url_for('questions.create_question', list_id=list.id)}}">Add question</a>
              </ul>
          </div>
        </div>
      </div>
      <div class="col-5">
        <div class="card text-center lbbg">
          <div class="card-body">
            <h5 class="card-title largeFont">{{ list.title }}: Flavour Text</h5>
              <ul class="list-group list-group-flush">
                  {% for ftext in list.flavour_text %}
                  <a class="list-group-item list-group-item-active" href="{{ url_for('questions.edit_flavour_text', list_id=list.id, flavour_text_id=ftext.id)}}">{{ ftext.text }}</a>
                  {% endfor %}
                  <a class="list-group-item list-group-item-active" href="{{ url_for('questions.create_flavour_text', list_id=list.id)}}">Add flavour text</a>
              </ul>
          </div>
        </div>
      </div>
    </div>
  </div>
</main>
{% endblock %}

{% block footer %}
{% include 'footer.html' %}
{% endblock %}

templates/questions/question.html
{% extends 'base.html' %}

{% block nav %}
{% with current='questions' %}
{% include 'nav.html' %}
{% endwith %}
{% endblock %}


{% block content %}
<header class="alignment">
  <div>
    <img class='logoImage' alt='logo' src="{{ url_for('static', filename='images/manyHex.png')}}">
  </div>
  <div>
    <h1 class="title">breakingboundr.io</h1>
  </div>
</header>
<main>
  <div class="card text-center lbbg">
    <div class="card-body" id='mainFont'>
      <h5 class="card-title largeFont"><a href="{{ url_for('questions.view_list', list_id=list.id) }}">{{list.title}}</a></h5>
        <ul class="list-group list-group-flush">
            <li class="list-group-item list-group-item-active">{{ question.question }}</li>
            <li class="list-group-item list-group-item-active">{{ question.answer }}</li>
        </ul>
    </div>
  </div>
</main>
{% endblock %}

{% block footer %}
{% include 'footer.html' %}
{% endblock %}