app/account/__init__.py
from . import routes

from .routes import bp

app/account/routes.py
from flask import Blueprint
from flask_login import current_user


bp = Blueprint('acc', __name__)

@bp.route('/account', methods=['GET', 'POST'])
def account():
    if current_user.is_authenticated:
        return str(current_user.username)
    
    
    
     ####display account info, inventory, profile picture etc.

app/main/routes.py
from flask import Blueprint, render_template


bp = Blueprint('main', __name__)


@bp.route('/')
def index():
    return render_template('index.html')

@bp.route('/rules')
def rules():
    return render_template('rules.html')

@bp.route('/game')
def game():
    return render_template('game.html')

@bp.route('/test_game')     # change to game.html later
def test_game():
    return render_template('test_game.html')

@bp.route('/contribution')
def contribution():
    return render_template('contribution.html')

templates/_formhelpers.html
{% macro render_field(field) %}
{% if field.type  == 'BooleanField' %}
  <dt> {{ field.label(class="sr-only") }}</dt>
  <dd>{{ field(**kwargs)|safe }} {{ field.label(class='darkBlue titlecard') }}</dd>
{% else %}
  <dt>{{ field.label(class='darkBlue titlecard') }}</dt>
  <dd>{{ field(**kwargs)|safe }}</dd>
  {% if field.errors %}
    <ul class="errors">
    {% for error in field.errors %}
      <li>{{ error }}</li>
    {% endfor %}
    </ul>
  {% endif %}
{% endif %}
{% endmacro %}

templates/account.html
{% extends 'base.html' %}

{% block nav %}
{% with current='account' %}
{% include 'nav.html' %}
{% endwith %}
{% endblock %}

{% block content %}
<header class="titlecard">
  <h1>Account</h1>
</header>
<main></main>
{% endblock %}

{% block footer %}
{% include 'footer.html' %}
{% endblock %}

templates/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <link
      rel="stylesheet"
      href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
      integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z"
      crossorigin="anonymous"
    />
    <link rel="icon" href="{{ url_for('static', filename='images/logoForPage.png')}}"/>
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Goldman&display=swap" rel="stylesheet">  
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Titillium+Web:wght@300&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="{{ url_for('static', filename='main.css')}}" />
    {% block styles %}{% endblock %}
    <title>breakingboundr.io</title>
  </head>

  <body>
{% block nav %}{% endblock %}
{% block content %}{% endblock %}
{% block footer %}{% endblock %}
    <script
      src="https://code.jquery.com/jquery-3.3.1.slim.min.js"
      integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"
      integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1"
      crossorigin="anonymous"
    ></script>
    <script
      src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"
      integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM"
      crossorigin="anonymous"
    ></script>
    {% block scripts %}{% endblock %}
  </body>
</html>

templates/contribution.html
{% extends 'base.html' %}

{% block nav %}
{% with current='contribution' %}
{% include 'nav.html' %}
{% endwith %}
{% endblock %}


{% block content %}
<header class="title">
  <div>
    <img class='smallLogo' alt='logo' src="{{ url_for('static', filename='images/logoForPage.png')}}">
  </div>
  <h1>CONTRIBUTORS</h1>
  <h2 class='white'> - THE TEAM - </h2>
</header>
<main>
<!-- carousel -->
  <body>
    <div class="card text-center lbbg marginspace">
      <div class="card-body">
        <h5 class="card-title largeFont titlecard">Who are we?</h5>
        <p class="card-text medFont">
          We are a team of computer science students and physics students from St Aidan's College (really, we're not from Trevs).
          <br>We wanted to create a game that incorporated the theme of 'Breaking Boundaries' as well as being educational.</br>
        </p>
      </div>
    </div>
  </body>
  <div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
    <div class="carousel-inner">
      <div class="carousel-item active">
        <img class='imagesizing centered' alt='ben' src="{{ url_for('static', filename='images/ben.jpg')}}">
        <p class='white centered titlecard'>Ben</p>
        <p class='white centered'>Developed Flask backend to serve JSON objects to client, database models with SQLAlchemy</p>
      </div>
      <div class="carousel-item">
        <img class='imagesizing centered' alt='johnny' src="{{ url_for('static', filename='images/johnny.jpg')}}">
        <p class='white centered titlecard'>Gianluca</p>
        <p class='white centered'>Worked on Flask and created promotional video</p>
      </div>
      <div class="carousel-item">
        <img class='imagesizing centered' alt='dave' src="{{ url_for('static', filename='images/dave.jpg')}}">
        <p class='white centered titlecard'>David</p>
        <p class='white centered'>Implemented torus hex grid and game UI</p>
      </div>
      <div class="carousel-item">
        <img class='imagesizing centered' alt='mairi' src="{{ url_for('static', filename='images/mairi.jpg')}}">
        <p class='white centered titlecard'>Mairi</p>
        <p class='white centered'>Designed and created static webpages with HTML and CSS</p>
      </div>
      <div class="carousel-item">
        <img class='imagesizing centered' alt='franek' src="{{ url_for('static', filename='images/franek.png')}}">
        <p class='white centered titlecard'>Franek</p>
        <p class='white centered'>Launched the flask app on a AWS EC2 instance using WSGGI and nginx</p>
      </div>
      <div class="carousel-item">
        <img class='imagesizing centered' alt='faiz' src="{{ url_for('static', filename='images/faiz.png')}}">
        <p class='white centered titlecard'>Faiz</p>
        <p class='white centered'>Worked off David's hexagon grid as a base to add question popup functionality, and used jQuery & AJAX for client-server communication along with flavour text</p>
      </div>
    </div>
    <a class="carousel-control-prev" href="#carouselExampleControls" role="button" data-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carouselExampleControls" role="button" data-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>
</main>
{% endblock %}

{% block footer %}
{% include 'footer.html' %}
{% endblock %}

templates/footer.html
<footer class="white">
  <div class="copyright py-4 text-center text-white" style="background-color: #0c0916">
    <div class="container">
      <a href="https://www.durhack.com">DurHack 2020</a> - Team BreakingBoundrio
    </div>
  </div>
</footer>

templates/formsExample.html
{% extends 'base.html' %}

{% block nav %}
{% with current='home' %}
{% include 'nav.html' %}
{% endwith %}
{% endblock %}


{% block content %}
<main>
    <div class='card gapsBetween'>
        <form class='formStyle'>
          <div class="class text-center">
            <div class="form-group">
                <label class='darkBlue titlecard' for="exampleInputEmail1">Email address</label>
                <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp" placeholder="Enter email" required="required">
              </div>
            <div class="form-group">
                <label class='darkBlue titlecard' for="exampleInputPassword1">Password</label>
                <input type="password" class="form-control" id="exampleInputPassword1" placeholder="Password">
            </div>
            <button type="button" class="btn btn-secondary" data-toggle="modal" data-target="#exampleModal">Submit</button>
          </div>
        </form>  
      </div>
      <!-- Modal -->
      <div class="modal" id="exampleModal" tabindex="-1" role="dialog">
        <div class="modal-dialog" role="document">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title">Submission Received</h5>
              <button
                type="button"
                class="close"
                data-dismiss="modal"
                aria-label="Close">
                <span aria-hidden="true">&times;</span>
              </button>
            </div>
            <div class="modal-body ">
              <p>Thanks for submitting!</p>
            </div>
            <div class="modal-footer">
              <button
                type="button"
                class="btn btn-secondary"
                data-dismiss="modal">
                Close
              </button>
            </div>
          </div>
        </div>
      </div>
</main>
{% endblock %}

templates/game.html
{% extends 'base.html' %}
{% block styles %}    
<link rel="stylesheet" href="{{ url_for('static', filename='game.css')}}" />
{% endblock %}

{% block nav %}
{% with current='game' %}
{% include 'nav.html' %}
{% endwith %}
{% endblock %}

{% block content %}
<div id="loading">
<h1> Loading...</h1>
</div>
<div class="question" style="display: none;" tabindex="-1" role="dialog">
	<div class="modal-dialog" role="document">
		<div class="modal-content">
			<div class="modal-header">
				<h5 class="modal-title"></h5>
			</div>
			<div class="modal-body">
				<p class="question-text"></p>
				<input type="text" class="form-control" id="answer">
				<div class="error" style="display: none;">You must enter an answer!</div>
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-primary" id="submit-answer">Submit your answer</button>
				<button type="button" class="btn btn-secondary" data-dismiss="modal" id="run">Run away</button>
			</div>
		</div>
	</div>
</div>
{% endblock %} 


{% block scripts %}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="http://d3js.org/d3.v3.min.js"></script>
<script src="https://d3js.org/topojson.v1.min.js"></script>
<script src="{{ url_for('static', filename='hexDrawing.js')}}"></script>
{% endblock %}

templates/index.html
{% extends 'base.html' %}

{% block nav %}
{% with current='home' %}
{% include 'nav.html' %}
{% endwith %}
{% endblock %}


{% block content %}
<header class="alignment">
  <div class="container-flex">
    <div class="row">
      <div class="col-12">
        <h1 class="title w-100">breakingboundr.io</h1>
      </div>
    </div>
    <div class="row">
      <div class="col-10 offset-1 col-sm-6 offset-sm-3">
        <img class='logoImage w-100' alt='logo' src="{{ url_for('static', filename='images/manyHex.png')}}">
      </div>
    </div>
  </div>  
</header>
<main>
  <div class="card text-center dbbg">
    <div class="card-body white">
      <h5 class="card-title largestFont white">Break Boundaries, Learn New Things</h5>
      <p class="card-text medFont">
        An educational game where you have to use your knowledge to
        break boundaries and beat your high score!
      </p>
      <p id='italicsFont'>
        Are you ready to break boundaries?
      </p>
      <a href="game" class="btn btn-light btn-lg">Play Now</a>
    </div>
  </div>
</main>
{% endblock %}

{% block footer %}
{% include 'footer.html' %}
{% endblock %}

templates/nav.html
<nav class="navbar navbar-expand-lg navbar-dark" id="navbar">
  <button
    class="navbar-toggler"
    type="button"
    data-toggle="collapse"
    data-target="#navbarSupportedContent"
    aria-controls="navbarSupportedContent"
    aria-expanded="false"
    aria-label="Toggle navigation"
  >
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto medFont">
      <li class="nav-item {% if current == 'home' %}active{% endif %}">
        <a class="nav-link" href="{{ url_for('main.index') }}"
          >Home {% if current == 'home' %}<span class="sr-only">(current)</span>{% endif %}</a
        >
      </li>
      <li class="nav-item {% if current == 'rules' %}active{% endif %}">
        <a class="nav-link" href="{{ url_for('main.rules') }}">How To Play {% if current == 'rules' %}<span class="sr-only">(current)</span>{% endif %}</a>
      </li>
      <li class="nav-item {% if current == 'questions' %}active{% endif %}">
        <a class="nav-link" href="{{ url_for('questions.view_lists') }}">Question Lists {% if current == 'questions' %}<span class="sr-only">(current)</span>{% endif %}</a>
      </li>
      <li class="nav-item {% if current == 'contribution' %}active{% endif %}">
        <a class="nav-link" href="{{ url_for('main.contribution') }}">Contributors {% if current == 'contribution' %}<span class="sr-only">(current)</span>{% endif %}</a>
      </li>
    </ul>
    <button class="btn {% if current == 'game' %} btn-dark {% else %} btn-light {% endif %} ml-auto" onclick="window.location.replace('{{url_for('main.game')}}')">Play the game!</button>
  </div>
</nav>

templates/rules.html
{% extends 'base.html' %}

{% block nav %}
{% with current='rules' %}
{% include 'nav.html' %}
{% endwith %}
{% endblock %}

{% block content %}
<header class="title">
  <div class="container-flex">
    <div class="row">
      <div class="col-6 offset-3 col-sm-2 offset-sm-5">
        <img class='smallLogo w-100' alt='logo' src="{{ url_for('static', filename='images/logoForPage.png')}}">
      </div>
    </div>
    <div class="row">
      <div class="col-8 offset-2">
        <h1>HOW TO PLAY</h1>
      </div>
    </div>
  </div>
</header>
<main>
    <div class="card-group">
      <div class="card">
        <div class="card-body">
          <h5 class="card-title titlecard largeFont centered">CONTROLS</h5>
          <div>
            <img class='imagesizing centered' alt='ctrls' src="{{ url_for('static', filename='images/controls.png')}}">
          </div>
          <p class="card-text centered">
            The keys shown above link to the directions you will travel along the board.
          </p>
        </div>
      </div>
      <div class="card lbbg">
        <div class="card-body">
          <h5 class="card-title titlecard largeFont centered">INSTRUCTIONS</h5>
          <p class="card-text centered">
            <ol class='list-group list-group-flush medFont'>
              <li class="list-group-item">1) Land on a hexagon.</li>
              <li class="list-group-item">2) A question will appear - answer it!</li>
              <li class="list-group-item">3) Move to the next hexagon.</li>
              <li class="list-group-item">4) Score highly by answering more questions correctly.</li>
            </ol>
          </p>
        </div>
      </div>
    </div>
  <div class="card card-group text-center centered dbbg">
    <div class="card-body white">
      <p id='italicsFont'>
        Want to add your own questions to the game?
      </p>
      <a href="questions/create" class="btn btn-light btn-lg">Click Here</a>
    </div>
  </div>
</main>
{% endblock %}

{% block footer %}
{% include 'footer.html' %}
{% endblock %}